### ISSUE TITLE
Windows 11上0.9.0版本运行时间长后会查询超时

### ISSUE THREAD

**Issue by debugg-a** [mokeyish/smartdns-rs#431]
OS：Windows 11 23H2
smardns版本：0.9.0
现象：在系统不关机持续运行一段时间后，出现DNS查询超时
![image](https://github.com/user-attachments/assets/c88c09a4-0177-4a5f-94c1-d3c603fd453b)
打印的日志如下：
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:
overflow when subtracting duration from instant
thread 'smartdns-runtime' panicked at library\std\src\time.rs:433:33:

**Comment by mokeyish** [comment]
有没有能复现的最下配置，可能上游服务器，比如近期的阿里的限流，超时等原因导致的。

**Comment by debugg-a** [comment]
# 配置 bootstrap-dns，如不配置则调用系统的
server https://1.12.12.12/dns-query -bootstrap-dns -exclude-default-group
# 配置国内上游服务器
# TencentDNS
server https://doh.pub/dns-query -group doh-tencent -exclude-default-group
# AliDNS
server https://dns.alidns.com/dns-query -group doh-alidns -exclude-default-group
# 360DNS
server https://doh.360.cn/dns-query -group doh-cn -exclude-default-group
# OneDNS
server https://doh-pure.onedns.net/dns-query -group doh-cn -exclude-default-group
# 湖北中烟内部DNS
server 10.156.0.240 -group hbzy -exclude-default-group
# 配置国外上游服务器
server tls://9.9.9.9
server tls://1.0.0.1

**Comment by debugg-a** [comment]
`# 配置 bootstrap-dns，如不配置则调用系统的
server https://1.12.12.12/dns-query -bootstrap-dns -exclude-default-group
# 配置国内上游服务器
# TencentDNS
server https://doh.pub/dns-query -group doh-tencent -exclude-default-group
# AliDNS
server https://dns.alidns.com/dns-query -group doh-alidns -exclude-default-group
# 360DNS
server https://doh.360.cn/dns-query -group doh-cn -exclude-default-group
# OneDNS
server https://doh-pure.onedns.net/dns-query -group doh-cn -exclude-default-group
# 配置国外上游服务器
server tls://9.9.9.9
server tls://1.0.0.1`

**Comment by debugg-a** [comment]
```
# 配置 bootstrap-dns，如不配置则调用系统的
server https://1.12.12.12/dns-query -bootstrap-dns -exclude-default-group
# 配置国内上游服务器
# TencentDNS
server https://doh.pub/dns-query -group doh-tencent -exclude-default-group
# AliDNS
server https://dns.alidns.com/dns-query -group doh-alidns -exclude-default-group
# 360DNS
server https://doh.360.cn/dns-query -group doh-cn -exclude-default-group
# OneDNS
server https://doh-pure.onedns.net/dns-query -group doh-cn -exclude-default-group
# 配置国外上游服务器
server tls://9.9.9.9
server tls://1.0.0.1
# 配置国内的域名国内DNS解析
nameserver /domain-set:set-alibaba/doh-alidns
nameserver /domain-set:set-tencent/doh-tencent
nameserver /domain-set:set-cn/doh-cn
```

**Comment by xshzr** [comment]
同样0.9.0，windows10遇到同样问题。
![屏948](https://github.com/user-attachments/assets/bcf300f9-8127-443a-aeb4-f53128bded98)
smartdns刚启动时查询没问题，过几分钟到十几分钟（没有准确的数值但是很短。），再查询就开始超时。
服务里单纯重启smartdns，无效。
关闭Smartdns，删除硬盘里的缓存文件，再启动Smartdns。又正常了。然后过一会还会复现。
怀疑和缓存有关。

**Comment by mokeyish** [comment]
@xshzr 你禁用缓存看看，试一段时间看看？如果是的话，我着重检查这块代码。

我放我自己的 windows 上跑，也改了日志打印，观察，6 个小时都没出现这种问题，可能电脑核心数太多了😅

**Comment by xshzr** [comment]
设置了cache-size 0后，还别说，一下午都没有出现超时。。

**Comment by mokeyish** [comment]
> 设置了cache-size 0后，还别说，一下午都没有出现超时。。

那开启缓存，禁掉域名预读取呢？

**Comment by xshzr** [comment]
之前开启缓存时的相关配置，预读取已经是关闭的：
cache-size 30000
cache-file O:/smartdns/cache/dnscache.txt
cache-persist yes
cache-checkpoint-time 10800
prefetch-domain no
serve-expired yes
serve-expired-ttl 10000
serve-expired-reply-ttl 3
#serve-expired-prefetch-time 43200
rr-ttl-min 300

**Comment by mokeyish** [comment]
那可能是 messageType 错了，从缓存读取是要根据 DNS记录重建 Message 的，昨天看到这个错误顺便改了，然后我自己一边一直监控着，哪怕改成单个线程也没有这种问题（但这里说的是关于时间，超时的问题，也不太像 messageType 导致的）。

晚点我提交这个修复看看。

**Comment by mokeyish** [comment]
#433 

下载 https://github.com/mokeyish/smartdns-rs/actions/runs/11762199344

**Comment by xshzr** [comment]
> [#433 ](https://github.com/mokeyish/smartdns-rs/pull/433)
> 
> 下载 [https://github.com/mokeyish/smartdns-rs/actions/runs/11762199344 ](https://github.com/mokeyish/smartdns-rs/actions/runs/11762199344)

修复了，此贴以上提到的问题，我这里没有再出现。

不过我还有一个老问题，好几个版本都一样，就是安卓手机端，设置dns为开启smartdns服务的电脑ip地址后，部分解析就会出问题。比如微信公众号文章可以打开，但里面的图片无法显示，咸鱼可以打开，但是咸鱼的签到页面一直显示页面加载失败，咸鱼的图片可以打开，视频无法播放。

**Comment by debugg-a** [comment]
> #433
> 
> 下载 https://github.com/mokeyish/smartdns-rs/actions/runs/11762199344

该版本开启缓存，开始预读，不到3效时开始超时。
'''
cache-size 32768
cache-persist yes
'''
![image](https://github.com/user-attachments/assets/1c8a0f3a-882b-42a6-a463-eec51eadc204)

**Comment by debugg-a** [comment]
> > #433
> > 下载 https://github.com/mokeyish/smartdns-rs/actions/runs/11762199344
> 
> 该版本开启缓存，开始预读，不到3效时开始超时。
> 
> ```
> cache-size 32768
> cache-persist yes
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/176259746/384744756-1c8a0f3a-882b-42a6-a463-eec51eadc204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyODc5MzEsIm5iZiI6MTczMTI4NzYzMSwicGF0aCI6Ii8xNzYyNTk3NDYvMzg0NzQ0NzU2LTFjOGEwZjNhLTg4MmItNDJhNi1hNDYzLWVlYzUxZWFkYzIwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwMTEzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTNkMzU0MTQzODBlNjMxMDhhYTdjOWY3OGRhYmJhOGMxMjg3YTJhZmNlOTQxYjY2MjlkYjNlYTNlZmQ2ZjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mo-MC-GQks67Ii2BM9z3AsOetdtOXZOpZhq_pwfm-IA)

开启缓存
![image](https://github.com/user-attachments/assets/60e1d7c3-8af0-4cb1-9632-a375dd56e745)

**Comment by xshzr** [comment]
昨天下午好像确实没有遇到之前超时的问题，我也觉的好了，晚上关机了，今天开机后那个mp.weixin.qq.com又超时了，重启smartdns服务也没用。我的缓存是cache-checkpoint-time定期保存到硬盘上的。不知道是不是第二天读取硬盘的缓存出现什么问题？

这是今天重启smartdns后的一段日志：

> 2024-11-11 11:55:05.973:INFO:      _____                      _       _____  _   _  _____ 
2024-11-11 11:55:05.973:INFO:     / ____|                    | |     |  __ \| \ | |/ ____|
2024-11-11 11:55:05.973:INFO:    | (___  _ __ ___   __ _ _ __| |_    | |  | |  \| | (___  
2024-11-11 11:55:05.973:INFO:     \___ \| '_ ` _ \ / _` | '__| __|   | |  | | . ` |\___ \ 
2024-11-11 11:55:05.973:INFO:     ____) | | | | | | (_| | |  | |_    | |__| | |\  |____) |
2024-11-11 11:55:05.973:INFO:    |_____/|_| |_| |_|\__,_|_|   \__|   |_____/|_| \_|_____/ 
2024-11-11 11:55:05.973:INFO: 
2024-11-11 11:55:05.973:INFO: awaiting connections...
2024-11-11 11:55:05.973:INFO: server starting up
2024-11-11 11:55:06.181:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:58204
2024-11-11 11:55:06.182:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:58204
2024-11-11 11:55:06.182:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:58204
2024-11-11 11:55:07.317:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.246:58356
2024-11-11 11:55:08.82:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:58655
2024-11-11 11:55:08.83:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:58655
2024-11-11 11:55:08.83:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:58655
2024-11-11 11:55:08.84:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:58655
2024-11-11 11:55:08.84:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:58655
2024-11-11 11:55:09.320:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.246:58357
2024-11-11 11:55:09.320:DEBUG:smartdns::app:363: Request: 11 src:udp://192.168.88.246#58357 type:QUERY dnssec:false QUERY:mp.weixin.qq.com.:AAAA:IN qflags:RD
2024-11-11 11:55:09.320:DEBUG:smartdns::app:374: Response: ; header 0:RESPONSE::NoError:QUERY:1/0/0
; query
;; mp.weixin.qq.com. IN AAAA
; answers 1
mp.weixin.qq.com. 300 IN SOA a.gtld-servers.net nstld.verisign-grs.com 1800 1800 900 604800 86400
; nameservers 0
; additionals 0
, Duration: 40µs
2024-11-11 11:55:09.321:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.246:58358
2024-11-11 11:55:10.614:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:59628
2024-11-11 11:55:10.614:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:59628
2024-11-11 11:55:10.615:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:59628
2024-11-11 11:55:10.615:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:59628
2024-11-11 11:55:10.616:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.198:59628
2024-11-11 11:55:11.335:DEBUG:smartdns::server::udp:45: received udp request from: 192.168.88.246:58359
2024-11-11 11:55:11.335:DEBUG:smartdns::app:363: Request: 13 src:udp://192.168.88.246#58359 type:QUERY dnssec:false QUERY:mp.weixin.qq.com.:AAAA:IN qflags:RD
2024-11-11 11:55:11.335:DEBUG:smartdns::app:374: Response: ; header 0:RESPONSE::NoError:QUERY:1/0/0
; query
;; mp.weixin.qq.com. IN AAAA
; answers 1
mp.weixin.qq.com. 300 IN SOA a.gtld-servers.net nstld.verisign-grs.com 1800 1800 900 604800 86400
; nameservers 0
; additionals 0
, Duration: 33.5µs

**Comment by mokeyish** [comment]
我这不好复现，帮忙定位下是什么问题。

1. 缓存预读取（禁掉预读取，开启缓存）
2. 缓存（禁掉缓存）
3. 测速（启用 fastest-response，这是最快响应，相当于不测速）

**Comment by xshzr** [comment]
缓存预读取我从来没开过，开启缓存，cache-checkpoint-time 300，清空硬盘缓存文件后，启动smartdns服务。解析正常。

等硬盘出现cache文件后，再测，仍然正常，服务里选择重新启动smartdns，也正常。

重启电脑，问题复现。怀疑是电脑关机时，smartdns服务不是正常退出的会出现什么问题，或开机后smartdns加载硬盘catch文件过程有问题。

![157](https://github.com/user-attachments/assets/d242c3e6-ba2d-4d92-9587-474265275334)
这是刚开机测试的，我的smartdns服务设置了延迟启动，之前老版本有问题，不延迟启动，有些解析会出问题，就一直设置延迟启动了。

**Comment by debugg-a** [comment]
> 我这不好复现，帮忙定位下是什么问题。
> 
> 1. 缓存预读取（禁掉预读取，开启缓存）
> 2. 缓存（禁掉缓存）
> 3. 测速（启用 fastest-response，这是最快响应，相当于不测速）

![image](https://github.com/user-attachments/assets/5b80451f-ca14-4f7d-a3a8-f32cd6198f13)

禁掉预读取，开启缓存------出现超时

**Comment by debugg-a** [comment]
> > 我这不好复现，帮忙定位下是什么问题。
> > 
> > 1. 缓存预读取（禁掉预读取，开启缓存）
> > 2. 缓存（禁掉缓存）
> > 3. 测速（启用 fastest-response，这是最快响应，相当于不测速）
> 
> ![image](https://private-user-images.githubusercontent.com/176259746/384805445-5b80451f-ca14-4f7d-a3a8-f32cd6198f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDgwNDMsIm5iZiI6MTczMTMwNzc0MywicGF0aCI6Ii8xNzYyNTk3NDYvMzg0ODA1NDQ1LTViODA0NTFmLWNhMTQtNGY3ZC1hM2E4LWYzMmNkNjE5OGYxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwNjQ5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjkwZWEyNzI3YTc3ZTdmYTVmYmNhZmVmMTU2MTM3NDgzZDkxMmRhMzdkM2M5Njg5MTA5Yzk2NTM0OGQzY2M1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mMUIHLBWIEYlnLBfI7oN8gHT1ZJZuOU0BHd8i4RYKNY)
> 
> 禁掉预读取，开启缓存------出现超时

禁掉预读取，开启缓存，启用 fastest-response------出现超时
![image](https://github.com/user-attachments/assets/2a682bdd-f6e9-4c8d-b4e0-743148e256de)

**Comment by mokeyish** [comment]
再做个测试，把 server 带域名的，给它指定一个 ip, 比如：
```ini
server https://cloudflare-dns.com/dns-query?ip=1.1.1.1
```

**Comment by debugg-a** [comment]
> 再做个测试，把 server 带域名的，**都**给它指定一个 ip, 比如：
> 
> ```ini
> server https://cloudflare-dns.com/dns-query?ip=1.1.1.1
> ```
> 
> 看看还会不会超时

![image](https://github.com/user-attachments/assets/a7c3855c-a418-46f2-8622-b717e4d0719d)

快一个小时了，还没有出现超时。

**Comment by xshzr** [comment]
说下我的一个观察到的规律，我的使用环境是把smartdns设在个人电脑上的，电脑每天都要关机的。

每次电脑开机后smartdns就会出现查询超时现象，一开始我以为是上次关机前保存在硬盘里的catch有问题，所以关闭smartdns，删除catch，启动smartdns，当时能查询了，但是，几分钟后查询过的域名就会再次超时，**直到过期缓存超时时间serve-expired-ttl 被触发**，一切都正常了。再也不超时了。serve-expired-ttl值设置5分钟，就5分钟后正常，1小时，就一小时后正常。

然后发现即使不关闭电脑，重启smartdns服务，又会再次出现上面出现的超时情况。并且重启过程是否删除硬盘缓存，并不会有大区别，唯一的区别就是删缓存，则第一次查询成功然后几分钟后超时，不删缓存，则直接超时。

并且超时后日志里只有AAAA的反馈，而没有A的反馈，即使指定-type=A也一样
2024-11-12 10:36:38.563:DEBUG:smartdns::app:363: Request: 11 src:udp://192.168.88.246#55040 type:QUERY dnssec:false QUERY:www.msn.com.:AAAA:IN qflags:RD
2024-11-12 10:36:38.563:DEBUG:smartdns::app:374: Response: ; header 0:RESPONSE::NoError:QUERY:1/0/0
; query
;; www.msn.com. IN AAAA
; answers 1
www.msn.com. 300 IN SOA a.gtld-servers.net nstld.verisign-grs.com 1800 1800 900 604800 86400
![0722](https://github.com/user-attachments/assets/a9d8fa8f-91e7-490b-ab08-c4bf652f208e)

**Comment by mokeyish** [comment]
我做了一个 DNS 性能测试的仓库。

https://github.com/mokeyish/dnsperf-testing

对本仓库依赖 hickory 进行测试，发现大量50%超时，然后老外测试，居然不能重现。你们看看，你们能重现么？依赖的测试工具 windows 可能没有，得装 WSL 。

下面是提交的 issue ，有说测试步骤。思路是直接对 119.29.29.29 进行测试，与通过 hickory 做转发 119.29.29.29 对比。

https://github.com/hickory-dns/hickory-dns/issues/2613

**Comment by mokeyish** [comment]
@xshzr 你说的规律，相当于控缓存了。现在发现可能是底层库 hickory 的问题，得先解决 hickory 超时问题，因为 smartdns-rs 依赖了它的 proto 协议库。

**Comment by blance714** [comment]
有一模一样的问题，也是不开cache就会恢复正常。
观察发现，只要开启了 `serve-expired`，会有第一次查询正常，等待dns记录过期，就会出现错误，百分百复现。

<details>
  <summary>Dig输出</summary>

  ```powershell
  PS D:\BIND9.17.12.x64> .\dig "@127.0.0.1" github.com
  
  ; <<>> DiG 9.17.12 <<>> @127.0.0.1 github.com
  ; (1 server found)
  ;; global options: +cmd
  ;; Got answer:
  ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59902
  ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
  
  ;; QUESTION SECTION:
  ;github.com.                    IN      A
  
  ;; ANSWER SECTION:
  github.com.             59      IN      A       140.82.116.3
  
  ;; Query time: 144 msec
  ;; SERVER: 127.0.0.1#53(127.0.0.1) (UDP)
  ;; WHEN: Tue Jan 07 18:14:54 China Standard Time 2025
  ;; MSG SIZE  rcvd: 44
  
  PS D:\BIND9.17.12.x64> .\dig "@127.0.0.1" github.com
  ;; Warning: ID mismatch: expected ID 63119, got 0
  ```
 
</details>

同时有时会出现的还有这个cache文件锁定失败的错误
```log
2025-01-07 18:23:17.112:DEBUG:smartdns::api::serve_dns:57: DoH POST https://127.0.0.1:4443/dns-query application/dns-message
2025-01-07 18:23:17.112:DEBUG:smartdns::api::serve_dns:57: DoH POST https://127.0.0.1:4443/dns-query application/dns-message
thread 'smartdns-runtime2025-01-07 18:23:17.113:DEBUG:smartdns::dns_mw_cache:504: Get dns cache lock to read failed, TryLockError(())
' panicked at std\src\time.rs2025-01-07 18:23:17.113:DEBUG:smartdns::dns_mw_ns:97: query name: collector.github.com. type: HTTPS via [Group: default]
:433:33:
overflow when subtracting duration from instant
```

<details>
  <summary>配置文件</summary>
  
  ```config
  bind 0.0.0.0:53
  bind-https :4443
  bind-cert-file smartdns.crt
  bind-cert-key-file smartdns.key
  cache-persist yes
  cache-file smartdns.cache
  serve-expired yes
  serve-expired-ttl 259200
  log-level debug
  log-console yes
  server 223.5.5.5
  ```
</details>

**Comment by mokeyish** [comment]
@blance714 感谢测试分析。周末先按这策略调整。

https://github.com/mokeyish/smartdns-rs/issues/456#issuecomment-2578712108

我们在这个 issue 上跟踪这个问题。
