### ISSUE TITLE
请问大佬，该项目是否适配了pymumu大佬的luci？

### ISSUE THREAD

**Issue by zxlhhyccc** [mokeyish/smartdns-rs#53]
AX6（ipq807x）
1、我使用仓库的二进制替换pymumu大佬的二进制，pymumu大佬的luci下不能运行。。。。
2、openwrt下我编译的二进制替换也是不能在pymumu大佬的luci下运行。。。

**Comment by mokeyish** [comment]
还没有哦，理论上直接替换，修改下启动命令即可(这边多是子命令 run 下启动的)，配置文件是兼容的。

**Comment by zxlhhyccc** [comment]
> 还没有哦，理论上直接替换，修改下启动命令即可(这边多是子命令 run 下启动的)，配置文件是兼容的。

请问一下启动命令如何修改？

**Comment by mokeyish** [comment]
目测是[这里](https://github.com/pymumu/smartdns/blob/3d7a2a8d801f912a3dfadcf4619137287a33ec74/package/openwrt/files/etc/init.d/smartdns#L664)改，linux 建议还是用原版吧，这个版本功能还不全，macos、windows 没办法，可以直接下载这个 rust 版，正常用应该没问题，我自己是在 macos 上用的。

**Comment by zxlhhyccc** [comment]
> 目测是[这里](https://github.com/pymumu/smartdns/blob/3d7a2a8d801f912a3dfadcf4619137287a33ec74/package/openwrt/files/etc/init.d/smartdns#L664)改，linux 建议还是用原版吧，这个版本功能还不全，macos、windows 没办法，可以直接下载这个 rust 版，正常用应该没问题，我自己是在 macos 上用的。

改成什么命令呢？

**Comment by mokeyish** [comment]
`/usr/sbin/smartdns run -c $SMARTDNS_CONF`

**Comment by mokeyish** [comment]
我没折腾过，你最好备份，目测是还这里。

**Comment by zxlhhyccc** [comment]
> `/usr/sbin/smartdns run -c $SMARTDNS_CONF`

我试试能不能运行。。。

**Comment by zxlhhyccc** [comment]
> 我没折腾过，你最好备份，目测是改这里。

不能执行，是不是上游服务器之类的配置不一样？

**Comment by mokeyish** [comment]
一样的，你可以把配置文件拷贝到 windows 下，测一下是不是都正常，有些功能没覆盖到，你若发现可以提。

**Comment by zxlhhyccc** [comment]
> 一样的，你可以把配置文件拷贝到 windows 下，测一下是不是都正常，有些功能没覆盖到，你若发现可以提。

也有绑定设备等之类的功能吗？

**Comment by mokeyish** [comment]
那个还没有额，下周或者下周周看看加上吧

**Comment by mokeyish** [comment]
是因为这个报配置文件解析错误？我可以先把配置文件解析加上。

**Comment by zxlhhyccc** [comment]
> 那个还没有额，下周或者下下周看看加上吧

可能是绑定设备之类没有导致不能运行，请问与官方的那个配置你这里实现了哪些功能呢？

**Comment by zxlhhyccc** [comment]
> 是因为这个报配置文件解析错误？我可以先把配置文件解析加上。

你加上相关功能我再来测试一下，openwrt我能实现编译二进制出来

**Comment by mokeyish** [comment]
> 可能是绑定设备之类没有导致不能运行，请问与官方的那个配置你这里实现了哪些功能呢？


绑定设备也是刚加不久的功能，这边没及时跟上，那么涉及原有配置的解析，识别不了，自然就无法启动了，这个简单我我一会加上

**Comment by zxlhhyccc** [comment]
> > 可能是绑定设备之类没有导致不能运行，请问与官方的那个配置你这里实现了哪些功能呢？
> 
> 绑定设备也是刚加不久的功能，这边没及时跟上，那么涉及原有配置的解析，识别不了，自然就无法启动了，这个简单我我一会加上

好的

**Comment by mokeyish** [comment]
解析 `@device` 先加上了 https://github.com/mokeyish/smartdns-rs/pull/54 ，你自行编译？我就不发 release 了。

![图片](https://user-images.githubusercontent.com/16131917/224538297-47b64c61-df51-4509-857b-5a331912bf17.png)

**Comment by zxlhhyccc** [comment]
好的，晚上我来测试一下能否运行。。。。

**Comment by zxlhhyccc** [comment]
> > 可能是绑定设备之类没有导致不能运行，请问与官方的那个配置你这里实现了哪些功能呢？
> 
> 绑定设备也是刚加不久的功能，这边没及时跟上，那么涉及原有配置的解析，识别不了，自然就无法启动了，这个简单我我一会加上

大佬，测试了一下，luci还是不能运行。

**Comment by zxlhhyccc** [comment]
我在ubuntu下运行命令，报错：
![image](https://user-images.githubusercontent.com/45259624/224550781-d52ea7db-6fad-49c3-9c7f-48c63943b1e9.png)

**Comment by mokeyish** [comment]
你配置文件是怎么写的？

**Comment by zxlhhyccc** [comment]
> 你配置文件是怎么写的？

估计还是配置文件问题，我单独搞了个配置文件，在ubunutu下运行你看看log，感觉怎么解析到ipv6去了：
````
#  IPV4: 
bind :7153

log-level info
log-file /home/lin/smartdns.log
log-size 128k

server 1.12.12.12 -group china -exclude-default-group
server 101.6.6.6 -group china -exclude-default-group
````
`````
1678631809:INFO: Smart-DNS 🐋 0.3.0 starting
1678631809:INFO: whoami 👉 lin-virtual-machine
1678631809:INFO: upstream server: udp://1.12.12.12 [Group: china] 
1678631809:INFO: upstream server: udp://101.6.6.6 [Group: china] 
1678631809:INFO: listening for UDP on [::]:7153
1678631809:INFO: 
1678631809:INFO:      _____                      _       _____  _   _  _____ 
1678631809:INFO:     / ____|                    | |     |  __ \| \ | |/ ____|
1678631809:INFO:    | (___  _ __ ___   __ _ _ __| |_    | |  | |  \| | (___  
1678631809:INFO:     \___ \| '_ ` _ \ / _` | '__| __|   | |  | | . ` |\___ \ 
1678631809:INFO:     ____) | | | | | | (_| | |  | |_    | |__| | |\  |____) |
1678631809:INFO:    |_____/|_| |_| |_|\__,_|_|   \__|   |_____/|_| \_|_____/ 
1678631809:INFO: 
1678631809:INFO: awaiting connections...
1678631809:INFO: server starting up
1678631815:INFO: terminating...
1678631815:INFO: SmartDNS 0.3.0 shutdown
`````

**Comment by mokeyish** [comment]
监听到 ipv6 ？你填 0.0.0.0:7153 就是了。

**Comment by zxlhhyccc** [comment]
> 监听到 ipv6 ？你填 0.0.0.0:7153 就是了。

我在路由上单独执行：./smartdns run -c /etc/smartdns/custom.conf，为什么出现两个一样的dns：
配置文件： 
````
log-level info
log-file /home/lin/smartdns.log
log-size 128k

# 国内 DNS
bind :53@br-lan -no-dualstack-selection -force-aaaa-soa speed-check-mode ping,tcp:80,tcp:443
bind :53@lo -no-dualstack-selection -force-aaaa-soa speed-check-mode ping,tcp:80,tcp:443

server 1.12.12.12
server 101.6.6.6
server 114.114.114.114


# 国外DNS
bind :5335@br-lan -group fq_dns -no-speed-check -no-dualstack-selection -force-aaaa-soa
bind :5335@lo -group fq_dns -no-speed-check -no-dualstack-selection -force-aaaa-soa
bind-tcp :5335@br-lan -group fq_dns -no-speed-check -no-dualstack-selection -force-aaaa-soa
bind-tcp :5335@lo -group fq_dns -no-speed-check -no-dualstack-selection -force-aaaa-soa

server 9.9.9.9 -group fq_dns -exclude-default-group
server 64.6.64.6 -group fq_dns -exclude-default-group
server 64.6.65.6 -group fq_dns -exclude-default-group
server 76.76.19.19 -group fq_dns -exclude-default-group
server 101.101.101.101 -group fq_dns -exclude-default-group
server 208.67.222.222 -group fq_dns -exclude-default-group
server 208.67.220.220 -group fq_dns -exclude-default-group
````
log:
```
1678632809:INFO: listening for UDP on [::]:6053
1678632919:INFO: Smart-DNS 🐋 0.3.0 starting
1678632919:INFO: whoami 👉 openwrt
1678632919:INFO: upstream server: udp://9.9.9.9 [Group: fq_dns] 
1678632919:INFO: upstream server: udp://64.6.64.6 [Group: fq_dns] 
1678632919:INFO: upstream server: udp://64.6.65.6 [Group: fq_dns] 
1678632919:INFO: upstream server: udp://76.76.19.19 [Group: fq_dns] 
1678632919:INFO: upstream server: udp://101.101.101.101 [Group: fq_dns] 
1678632919:INFO: upstream server: udp://208.67.222.222 [Group: fq_dns] 
1678632919:INFO: upstream server: udp://208.67.220.220 [Group: fq_dns] 
1678632919:INFO: upstream server: udp://1.12.12.12 [Group: default]
1678632919:INFO: upstream server: udp://1.12.12.12 [Group: default]
1678632919:INFO: upstream server: udp://101.6.6.6 [Group: default]
1678632919:INFO: upstream server: udp://101.6.6.6 [Group: default]
1678632919:INFO: upstream server: udp://114.114.114.114 [Group: default]
1678632919:INFO: upstream server: udp://114.114.114.114 [Group: default]
````

**Comment by mokeyish** [comment]
谢谢反馈，重复添加默认分组的问题已经在 #55 修复

**Comment by mokeyish** [comment]
![图片](https://user-images.githubusercontent.com/16131917/224555466-de2c07fc-13ab-4564-8653-35280229b51e.png)
这里少了，横杠开头

**Comment by mokeyish** [comment]
你这都用 udp 的么？这个不安全啊，中间人都能使用抓包工具，可以看到你访问的域名记录的。

**Comment by zxlhhyccc** [comment]
> 你这都用 udp 的么？这个不安全啊，中间人都能使用抓包工具，可以看到你访问的域名记录的。

我是测试一下。。随便填的。。。

**Comment by mokeyish** [comment]
> > 还没有哦，理论上直接替换，修改下启动命令即可(这边多是子命令 run 下启动的)，配置文件是兼容的。
> 
> 请问一下启动命令如何修改？能否写一个启动脚本呢？另外，我能否把openwrt下可编译的Makefile提pr放入仓库？

好，你放到 contrib 目录下吧，`/contrib/openwrt` 这样？

**Comment by zxlhhyccc** [comment]
> > > 还没有哦，理论上直接替换，修改下启动命令即可(这边多是子命令 run 下启动的)，配置文件是兼容的。
> > 
> > 
> > 请问一下启动命令如何修改？能否写一个启动脚本呢？另外，我能否把openwrt下可编译的Makefile提pr放入仓库？
> 
> 好，你放到 contrib 目录下吧，`/contrib/openwrt` 这样？

可以的，明天我pr上来可以吧？

**Comment by mokeyish** [comment]
我自己路由器是 x86_64 架构的 openwrt 一般直接拿 Github action 自动打包的 linux_x86_64_musl 去就可以运行了，我自己也没用，现在还不如 c 版完善。主要还是 macos 上面自用。

**Comment by zxlhhyccc** [comment]
> 我自己路由器是 x86_64 架构的 openwrt 一般直接拿 Github action 自动打包的 linux_x86_64_musl 去就可以运行了，我自己也没用，现在还不如 c 版完善。主要还是 macos 上面自用。

这是什么情况，测速有问题：
````
log-level info
log-file /home/lin/smartdns.log
log-size 128k

# 国内 DNS
bind :53@br-lan -no-dualstack-selection -force-aaaa-soa speed-check-mode ping,tcp:80,tcp:443
bind :53@lo -no-dualstack-selection -force-aaaa-soa speed-check-mode ping,tcp:80,tcp:443

server 1.12.12.12
server 101.6.6.6
server 114.114.114.114


# 国外DNS
bind :5335@br-lan -group fq_dns -no-speed-check -no-dualstack-selection -force-aaaa-soa
bind :5335@lo -group fq_dns -no-speed-check -no-dualstack-selection -force-aaaa-soa
bind-tcp :5335@br-lan -group fq_dns -no-speed-check -no-dualstack-selection -force-aaaa-soa
bind-tcp :5335@lo -group fq_dns -no-speed-check -no-dualstack-selection -force-aaaa-soa

server 9.9.9.9 -group fq_dns -exclude-default-group
server 64.6.64.6 -group fq_dns -exclude-default-group
server 64.6.65.6 -group fq_dns -exclude-default-group
server 76.76.19.19 -group fq_dns -exclude-default-group
server 101.101.101.101 -group fq_dns -exclude-default-group
server 208.67.222.222 -group fq_dns -exclude-default-group
server 208.67.220.220 -group fq_dns -exclude-default-group
log:
````
root@OpenWrt:/usr/sbin# ./smartdns run -c /usr/custom.conf
1678636949:INFO: Smart-DNS 🐋 0.3.0 starting
1678636949:INFO: loading configuration from: "/usr/custom.conf"
1678636949:WARN:smartdns::dns_conf:842: unknown option: -speed-check-mode
1678636949:ERROR:smartdns::dns_conf:847: unexpected options: ping,tcp:80,tcp:443
1678636949:WARN:smartdns::dns_conf:842: unknown option: -speed-check-mode
1678636949:ERROR:smartdns::dns_conf:847: unexpected options: ping,tcp:80,tcp:443
1678636949:INFO: whoami 👉 openwrt
1678636949:INFO: upstream server: udp://9.9.9.9 [Group: fq_dns]
1678636949:INFO: upstream server: udp://64.6.64.6 [Group: fq_dns]
1678636949:INFO: upstream server: udp://64.6.65.6 [Group: fq_dns]
1678636949:INFO: upstream server: udp://76.76.19.19 [Group: fq_dns]
1678636949:INFO: upstream server: udp://101.101.101.101 [Group: fq_dns]
1678636949:INFO: upstream server: udp://208.67.222.222 [Group: fq_dns]
1678636949:INFO: upstream server: udp://208.67.220.220 [Group: fq_dns]
1678636949:INFO: upstream server: udp://1.12.12.12 [Group: default]
1678636949:INFO: upstream server: udp://101.6.6.6 [Group: default]
1678636949:INFO: upstream server: udp://114.114.114.114 [Group: default]
thread 'main' panicked at 'could not bind to udp: [::]:53', src/main.rs:268:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```````

**Comment by mokeyish** [comment]
53 监听端口重复了，现在只是解析了设备名，并没有实现，注销掉一个选项去。


测速那个选项也没实现解析，代码在这😂
https://github.com/mokeyish/smartdns-rs/blob/9f87f49a5e441c518afd8f7f99e048cf9675764f/src/dns_conf.rs#L823–L854

**Comment by zxlhhyccc** [comment]
> 53 监听端口重复了，现在只是解析了设备名，并没有实现，注销掉一个选项去。
> 
> 测速那个选项也没实现解析，代码在这😂
> 
> https://github.com/mokeyish/smartdns-rs/blob/9f87f49a5e441c518afd8f7f99e048cf9675764f/src/dns_conf.rs#L825-L849

这个代码是实现测速用的吗？

**Comment by mokeyish** [comment]
测速逻辑都实现了，有 ping,tcp，还有原 c 版没有的 http 和 https，在下面这

https://github.com/mokeyish/smartdns-rs/blob/9f87f49a5e441c518afd8f7f99e048cf9675764f/src/infra/ping.rs#L38

只不过，现在是以我自身使用优先实现的，测试还不到位，你也可以来帮忙一起完善，目前代码应该不算复杂吧，另外 dhcp 也会集成来的，已经找到合适的类库了。

**Comment by zxlhhyccc** [comment]
> 测速逻辑都实现了，有 ping, tcp，还有原 c 版没有的 http 和 https，在下面这
> 
> https://github.com/mokeyish/smartdns-rs/blob/9f87f49a5e441c518afd8f7f99e048cf9675764f/src/infra/ping.rs#L38
> 
> 只不过，现在是以我自身使用优先实现的，测试还不到位，你也可以来帮忙一起完善，目前代码应该不算复杂吧，另外 dhcp 也会集成来的，已经找到合适的类库了。

测速逻辑都实现了的话，该怎么写呢？

**Comment by mokeyish** [comment]
那个文件最下面有单元测试，就是 ping 测速的用法。

**Comment by zxlhhyccc** [comment]
> 那个文件最下面有单元测试，就是 ping 测速的用法。

明天看看，不知道我看得懂不。

**Comment by zxlhhyccc** [comment]
大佬，你这里有测速写法，为何实际测速出现错误：
![image](https://user-images.githubusercontent.com/45259624/224609232-43d789f4-5b78-4c01-bde5-a3a51b632311.png)

**Comment by mokeyish** [comment]
实现了，有没有正确用上，这个还要另说的，需要测试，比如在这里的 http/https 注释就忘记更新了。

**Comment by zxlhhyccc** [comment]
> 实现了，有没有正确用上，这个还要另说的，需要测试，比如在这里的 http/https 注释就忘记更新了。

那应该咋写？对了，Makefile我已经pr上来了，你合并一下。。

**Comment by mokeyish** [comment]
咋写，得你自己看了，只能跟你讲流程，从 main.rs 的 main 函数进入 => 解析命令行参数 => 读取配置文件=>构建中间件(middleware[代码在这里](https://github.com/mokeyish/smartdns-rs/blob/9f87f49a5e441c518afd8f7f99e048cf9675764f/src/main.rs#L193))=>监听端口。

主要逻辑在 middleware 那里，middleware 是分文件实现的，缓存的有 dns_mw_cache.rs、查询审计的有 dns_mw_audit.rs、查询分组策略的是 dns_mw_ns.rs

最简单的一个中间件是 `dns_mw_bogus.rs`, 它是做假冒地址过滤的 36 行代码。

**Comment by zxlhhyccc** [comment]
按照此处写的方法，测速还是意想不到的选项，失败：
![image](https://user-images.githubusercontent.com/45259624/224727068-ef3eeb8b-7781-4126-9e27-bb5707d14025.png)
````

root@OpenWrt:~# ./smartdns run -c custom.conf
1678716695:INFO: Smart-DNS 🐋 0.3.0 starting
1678716695:INFO: loading configuration from: "custom.conf"
1678716695:ERROR:smartdns::dns_conf:847: unexpected options: speed-check-mode
1678716695:ERROR:smartdns::dns_conf:847: unexpected options: ping,tcp::443
1678716695:INFO: whoami 👉 openwrt
1678716695:INFO: upstream server: udp://9.9.9.9 [Group: fq_dns]
1678716695:INFO: upstream server: udp://64.6.64.6 [Group: fq_dns]
1678716695:INFO: upstream server: udp://64.6.65.6 [Group: fq_dns]
1678716695:INFO: upstream server: udp://76.76.19.19 [Group: fq_dns]
1678716695:INFO: upstream server: udp://101.101.101.101 [Group: fq_dns]
1678716695:INFO: upstream server: udp://208.67.222.222 [Group: fq_dns]
1678716695:INFO: upstream server: udp://208.67.220.220 [Group: fq_dns]
1678716695:INFO: upstream server: udp://1.12.12.12 [Group: default]
1678716695:INFO: upstream server: udp://101.6.6.6 [Group: default]
1678716695:INFO: upstream server: udp://114.114.114.114 [Group: default]
thread 'main' panicked at 'could not bind to udp: [::]:53', src/main.rs:268:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``````

**Comment by mokeyish** [comment]
这个错误忽略吧，不影响使用，C 版文档，也没有直接在 bind 上写测试模式的，只有-no-speed-check的选项

![图片](https://user-images.githubusercontent.com/16131917/224728488-b7523282-43ce-4708-bc1e-9bad3d57d29b.png)

**Comment by zxlhhyccc** [comment]
测速模式写到dns上面没问题，能正常。。。
现在有个问题就是，rust版本貌似不能在原版的luci下运行。。。

**Comment by mokeyish** [comment]
> 测速模式写到dns上面没问题，能正常。。。 现在有个问题就是，rust版本貌似不能在原版的luci下运行。。。

这个你研究下，我也没折腾过。跟原版的区别就是启动多了个 `run` 子命令，可能还有地方没改到位。

**Comment by zxlhhyccc** [comment]
> > 测速模式写到dns上面没问题，能正常。。。 现在有个问题就是，rust版本貌似不能在原版的luci下运行。。。
> 
> 这个你研究下，我也没折腾过。跟原版的区别就是启动多了个 `run` 子命令，可能还有地方没改到位。

可能是没有原版的一些功能导致不能运行，如果是命令行运行就正常使用，另外一个就是不知道能否绑定53端口（我没测试），我补丁其他端口没问题。。。

**Comment by mokeyish** [comment]
命令行正常使用，应该是没改全😂，比如原版 luci 调整完参数，是不是会自动调 service smartdns restart ，如果你带了–rs后缀，自然也不行。

**Comment by zxlhhyccc** [comment]
感觉这个运行起来也很好，不错不错，我先添加一个conf再说，等有时间我来搞一个简单的luci试试。只是暂时不知道你哪里没改全，只能一个一个的放到luci上去测试。。。。
原版我只改了这里：
![image](https://user-images.githubusercontent.com/45259624/224740785-267d3a29-c07b-4414-aa2a-013eda772094.png)

**Comment by mokeyish** [comment]
windows 下也可以帮忙测试的，windows 长期使用是否稳定还不知道。我就只在苹果电脑上用了几个月，还可以，有问题我自己都改好了。

**Comment by zxlhhyccc** [comment]
> windows 下也可以帮忙测试的，windows 长期使用是否稳定还不知道。我就只在苹果电脑上用了几个月，还可以，有问题我自己都改好了。

那个Makefile你可以合并的，我openwrt使用rust和Cargo是1.6.7版本编译的测试没问题。。。

**Comment by zxlhhyccc** [comment]
> windows 下也可以帮忙测试的，windows 长期使用是否稳定还不知道。我就只在苹果电脑上用了几个月，还可以，有问题我自己都改好了。

这个软件如何在后台运行？关闭窗口会自动停止，看样子真的要写一个luci来运行它。。。

**Comment by mokeyish** [comment]
openwrt 么？不用 luci 用 procd 封成服务就好了，我写了但也是没自己测试用过的。参考这里 https://github.com/mokeyish/smartdns-rs/blob/main/src/service/linux/initd/openwrt/files/etc/init.d/smartdns-rs


或者更通用的 tmux 帮你了。

**Comment by zxlhhyccc** [comment]
你这个脚本貌似是原版改的哦。。。。

**Comment by zxlhhyccc** [comment]
@mokeyish 用你的init不能运行。。。。

**Comment by zxlhhyccc** [comment]
我对照写了一个简单的脚本可以运行，但很奇怪的是脚本中测速必须放到绑定端口，但命令行却要放到dns。。。
````
#!/bin/sh /etc/rc.common

USE_PROCD=1

# PROCD_DEBUG=1

START=90
STOP=10

NAME=smartdns
PROG="/usr/sbin/smartdns"
CONF_FILE="etc/smartdns/custom.conf"

start_service(){
    procd_open_instance $PROG
    procd_set_param command $PROG run -c $CONF_FILE
    procd_set_param file $CONF_FILE
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5} # respawn automatically if something died, be careful if you have an alternative process supervisor
    procd_close_instance
}

stop_service(){
    service_stop $NAME
}

reload_service(){
    service_reload $NAME
}
`````

**Comment by mokeyish** [comment]
测速的还不算稳定，处理逻辑可能有问题需要检查。对于网站，其实用 `https` 比 `tcp:443` 好，tcp 测的可能是与中转代理的延时。

**Comment by zxlhhyccc** [comment]
> 测速的还不算稳定，处理逻辑可能有问题需要检查。对于网站，其实用 `https` 比 `tcp:443` 好，tcp 测的可能是与中转代理的延时。

能否把测速的处理逻辑修修？另外，你的这个版本貌似占用内存比原版的小，现在就是搞一个luci在页面操作。

**Comment by zxlhhyccc** [comment]
周末搞一个luci试试。。。

**Comment by zxlhhyccc** [comment]
你说的技术栈是指啥？你搞个独立的web界面也不错，总比没有luci好。。。。

**Comment by mokeyish** [comment]
技术栈就是问你，会哪些编程语言，会不会 web 开发，会的话开发个 web 管理界面，参考 adguardhome 或者 luci 的界面。

我是有心无力，没时间开发 web 管理了。等这个功能基本覆盖完成，想去研究写个 p2p 的通讯软件，防止通讯内容被监控

**Comment by zxlhhyccc** [comment]
> 技术栈就是问你，会哪些编程语言，会不会 web 开发，会的话开发个 web 管理界面，参考 adguardhome 或者 luci 的界面。
> 
> 我是有心无力，没时间开发 web 管理了。等这个功能基本覆盖完成，想去研究写个 p2p 的通讯软件，防止通讯内容被监控

你的意思是说在二进制执行文件里显示web界面对吗？

**Comment by mokeyish** [comment]
> 你的意思是说在二进制执行文件里显示web界面对吗？

是的，弄个 web 界面，调程序的接口，修改配置。web 的静态文件可以嵌进二进制里的。

**Comment by mokeyish** [comment]
绑定到设备已经支持了，https://github.com/mokeyish/smartdns-rs/pull/58

**Comment by zxlhhyccc** [comment]
ok，我昨晚搞了一下脚本测试了一晚上，就是不能执行luci的配置。。。

**Comment by zxlhhyccc** [comment]
> 绑定到设备已经支持了，#58

测试了最新的commit，luci里配置中如果绑定了端口，软件就不运行，如果不绑定端口，可以运行。。。
读取的可以运行的配置：
````
server-name smartdns
dualstack-ip-selection no
prefetch-domain yes
serve-expired yes
cache-size 32768
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 60
rr-ttl-max 86400
log-size 64K
log-num 1
log-level error
force-qtype-SOA  28 65
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
server 223.6.6.6:53  -group china -exclude-default-group 
server 114.114.114.114:53  -group china -exclude-default-group 
server-https https://8.8.4.4/dns-query  
server-https https://1.1.1.1/dns-query  
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf
````
读取luci的绑定端口不能运行（绑定了53和5335端口或者绑定一个端口）：
````
server-name smartdns
dualstack-ip-selection no
prefetch-domain yes
serve-expired yes
cache-size 32768
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 60
rr-ttl-max 86400
log-size 64K
log-num 1
log-level error
force-qtype-SOA  28 65
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
bind :53
bind :5335  -no-speed-check -no-dualstack-selection -force-aaaa-soa
bind-tcp :5335  -no-speed-check -no-dualstack-selection -force-aaaa-soa
server 223.6.6.6:53  -group china -exclude-default-group 
server 114.114.114.114:53  -group china -exclude-default-group 
server-https https://8.8.4.4/dns-query  
server-https https://1.1.1.1/dns-query  
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf
````

**Comment by mokeyish** [comment]
端口冲突么？把日志写到文件上，拿出来看看？

**Comment by zxlhhyccc** [comment]
````
1679125262:INFO: Smart-DNS 🐋 0.3.0 starting
1679125262:INFO: whoami 👉 smartdns
1679125262:INFO: upstream server: udp://223.6.6.6 [Group: china] 
1679125262:INFO: upstream server: udp://114.114.114.114 [Group: china] 
1679125262:INFO: upstream server: udp://1.12.12.12 [Group: china] 
1679125262:INFO: upstream server: udp://101.6.6.6 [Group: china] 
1679125262:INFO: upstream server: udp://101.226.4.6 [Group: china] 
1679125262:INFO: upstream server: udp://119.29.29.29 [Group: china] 
1679125262:INFO: upstream server: udp://123.125.81.6 [Group: china] 
1679125262:INFO: upstream server: udp://180.76.76.76 [Group: china] 
1679125262:INFO: upstream server: udp://202.101.224.69 [Group: china] 
1679125262:INFO: upstream server: udp://202.38.93.153 [Group: china] 
1679125262:INFO: upstream server: udp://202.141.162.123 [Group: china] 
1679125262:INFO: upstream server: udp://202.141.178.13 [Group: china] 
1679125262:INFO: upstream server: udp://223.5.5.5 [Group: china] 
1679125262:INFO: upstream server: tls://120.53.53.53 [Group: china] 
1679125262:INFO: upstream server: tls://rubyfish.cn [Group: china] 
1679125262:INFO: upstream server: tls://dot.360.cn [Group: china] 
1679125262:INFO: upstream server: tls://dot.pub [Group: china] 
1679125262:INFO: upstream server: https://dns.pub/dns-query [Group: china] 
1679125262:INFO: upstream server: https://1.12.12.12/dns-query [Group: china] 
1679125262:INFO: upstream server: https://doh.pub/dns-query [Group: china] 
1679125262:INFO: upstream server: https://doh.360.cn/dns-query [Group: china] 
1679125262:INFO: upstream server: https://223.5.5.5/dns-query [Group: china] 
1679125262:INFO: upstream server: https://223.6.6.6/dns-query [Group: china] 
1679125262:INFO: upstream server: https://dns.alidns.com/dns-query [Group: china] 
1679125262:INFO: upstream server: https://rubyfish.cn/dns-query [Group: china] 
1679125262:INFO: upstream server: https://8.8.4.4/dns-query [Group: default]
1679125262:INFO: upstream server: https://1.1.1.1/dns-query [Group: default]
1679125262:INFO: upstream server: udp://9.9.9.9 [Group: default]
1679125262:INFO: upstream server: udp://64.6.64.6 [Group: default]
1679125262:INFO: upstream server: udp://64.6.65.6 [Group: default]
1679125262:INFO: upstream server: udp://76.76.19.19 [Group: default]
1679125262:INFO: upstream server: udp://101.101.101.101 [Group: default]
1679125262:INFO: upstream server: udp://208.67.222.222 [Group: default]
1679125262:INFO: upstream server: udp://208.67.220.220 [Group: default]
1679125262:INFO: upstream server: tls://dns.google [Group: default]
1679125262:INFO: upstream server: https://dns.google/dns-query [Group: default]
1679125262:INFO: upstream server: tcp://1.0.0.1 [Group: default]
1679125262:INFO: upstream server: tcp://8.8.8.8 [Group: default]
1679125262:INFO: upstream server: tcp://149.112.112.112 [Group: default]
1679125262:INFO: upstream server: tls://1dot1dot1dot1.cloudflare-dns.com [Group: default]
1679125262:INFO: upstream server: tls://dns.google [Group: default]
1679125262:INFO: upstream server: tls://dns.adguard.com [Group: default]
1679125262:INFO: upstream server: tls://dns.twnic.tw [Group: default]
1679125262:INFO: upstream server: tls://185.222.222.222 [Group: default]
1679125262:INFO: upstream server: tls://185.184.222.222 [Group: default]
1679125262:INFO: upstream server: https://dns.quad9.net/dns-query [Group: default]
1679125262:INFO: upstream server: https://dns.adguard.com/dns-query [Group: default]
1679125262:INFO: upstream server: https://doh.dns.sb/dns-query [Group: default]
1679125262:INFO: upstream server: https://doh.opendns.com/dns-query [Group: default]
1679125262:INFO: upstream server: https://dns.twnic.tw/dns-query [Group: default]
1679125262:INFO: upstream server: https://103.121.210.210/dns-query [Group: default]
1679125262:INFO: upstream server: https://cloudflare-dns.com/dns-query [Group: default]
1679125262:INFO: upstream server: https://dns.google/dns-query [Group: default]
1679125262:INFO: upstream server: https://mozilla.cloudflare-dns.com/dns-query [Group: default]
1679125262:INFO: upstream server: https://doh.apad.pro/cdn-query [Group: default]
1679125262:INFO: upstream server: https://doh.cleanbrowsing.org/doh/security-filter [Group: default]
1679125262:INFO: listening for UDP on 0.0.0.0:53
1679125262:INFO: listening for UDP on 0.0.0.0:5335
`````

**Comment by mokeyish** [comment]
debug 也开吧，正常启动是会打印，

awaiting connections...
server starting up

**Comment by zxlhhyccc** [comment]
> debug 也开吧，正常启动是会打印，
> 
> awaiting connections... server starting up

已多次测试，如果luci配置绑定端口和设备，自定义配置就不得绑定端口和设备，反之也是一样。。。

**Comment by zxlhhyccc** [comment]
另外一个问题：
国外的DOH无法解析：
````
1679133431:INFO: awaiting connections...
1679133431:INFO: server starting up
1679133434:INFO: reading DNS cache from file: "/etc/smartdns/smartdns.cache"
1679133434:INFO: DNS cache 234 records loaded, elapsed 3.237652ms
1679133434:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for doh.cleanbrowsing.org.
1679133434:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for cloudflare-dns.com.
1679133434:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for dns.adguard.com.
1679133434:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for 1dot1dot1dot1.cloudflare-dns.com.
1679133434:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for doh.dns.sb.
1679133434:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for dns.google.
1679133434:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for dns.twnic.tw.
1679133434:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for dns.quad9.net.
1679133434:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for doh.apad.pro.
````

**Comment by zxlhhyccc** [comment]
还有一个问题，国外的DOH无法解析：
````
1679133584:INFO: awaiting connections...
1679133584:INFO: server starting up
1679133602:INFO: reading DNS cache from file: "/etc/smartdns/smartdns.cache"
1679133602:INFO: DNS cache 236 records loaded, elapsed 2.993069ms
1679133634:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for dns.twnic.tw.
1679133634:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for doh.apad.pro.
1679133634:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for cloudflare-dns.com.
1679133634:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for dns.google.
1679133635:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for 1dot1dot1dot1.cloudflare-dns.com.
1679133635:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for doh.cleanbrowsing.org.
1679133635:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for dns.adguard.com.
1679133635:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for doh.dns.sb.
1679133635:ERROR:smartdns::dns_mw_ns:91: no available nameserver found for dns.quad9.net.
``````

**Comment by mokeyish** [comment]
https://github.com/mokeyish/smartdns-rs/pull/60
