### ISSUE TITLE
为何运行cargo build --release编译失败？

### ISSUE THREAD

**Issue by zxlhhyccc** [mokeyish/smartdns-rs#7]
````
lin@lin-virtual-machine:~/图片/smartdns-rs$ cargo build --release
   Compiling smartdns v0.1.0 (/home/lin/图片/smartdns-rs)
warning: to use a constant of type `Ipv4Addr` in a pattern, `Ipv4Addr` must be annotated with `#[derive(PartialEq, Eq)]`
  --> src/preset_ns.rs:40:13
   |
40 |             CLOUDFLARE_IPS => "cloudflare-dns.com",
   |             ^^^^^^^^^^^^^^
   |
   = note: `#[warn(indirect_structural_match)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #62411 <https://github.com/rust-lang/rust/issues/62411>

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: FallbackToConstRef(())', compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs:164:83
stack backtrace:
   0:     0x7f3b6213f4fd - std::backtrace_rs::backtrace::libunwind::trace::h701a19af54e96518
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f3b6213f4fd - std::backtrace_rs::backtrace::trace_unsynchronized::h72ee8a54c0971fed
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f3b6213f4fd - std::sys_common::backtrace::_print_fmt::h107ba6740bde4568
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f3b6213f4fd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6ef53fbc8fdae4ac
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f3b6219935c - core::fmt::write::h65db65649c4a3094
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/fmt/mod.rs:1194:17
   5:     0x7f3b62130a51 - std::io::Write::write_fmt::h2a783718d67af8f3
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/io/mod.rs:1655:15
   6:     0x7f3b621425e5 - std::sys_common::backtrace::_print::he0510d2c6a87b26b
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f3b621425e5 - std::sys_common::backtrace::print::hd2a99ac691f33dce
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f3b621425e5 - std::panicking::default_hook::{{closure}}::hf449f9dd4998781a
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:295:22
   9:     0x7f3b62142299 - std::panicking::default_hook::he8f54f41bcecb62f
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:314:9
  10:     0x7f3b628c45a1 - rustc_driver[567d1d5f3a7c5811]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f3b4f9959a9 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb2816a6f3592cb95
  12:     0x7f3b4f9aea64 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::hadaaaee027d39c16
  13:     0x7f3b4f9bbd46 - std::panicking::update_hook::{{closure}}::h1a114f1cdbaa3a08
  14:     0x7f3b62142d30 - std::panicking::rust_panic_with_hook::h3c6fb7c0bbe9c7a1
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:702:17
  15:     0x7f3b62142b67 - std::panicking::begin_panic_handler::{{closure}}::h1fbef4cbf40a70cf
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:588:13
  16:     0x7f3b6213f9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h8fee2597b379cc21
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:138:18
  17:     0x7f3b62142899 - rust_begin_unwind
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:584:5
  18:     0x7f3b621069e3 - core::panicking::panic_fmt::h4c16adcdb276f16f
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/panicking.rs:143:14
  19:     0x7f3b62106ad3 - core::result::unwrap_failed::h4642b44f48942d78
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/result.rs:1785:5
  20:     0x7f3b63f5bd57 - <rustc_infer[3691bb34c1717fd7]::infer::InferCtxtBuilder>::enter::<rustc_middle[80ce3c200b65c1bf]::thir::Pat, <rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::PatCtxt>::const_to_pat::{closure#0}>
  21:     0x7f3b64b26510 - <rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::PatCtxt>::const_to_pat
  22:     0x7f3b63f304fe - <rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::PatCtxt>::lower_path
  23:     0x7f3b63f2cd6c - <rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::PatCtxt>::lower_pattern
  24:     0x7f3b63f67eb6 - <core[48d2d63575a1b4fb]::iter::adapters::map::Map<core[48d2d63575a1b4fb]::slice::iter::Iter<rustc_hir[8ae6c0dca9300fdf]::hir::Arm>, <rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::check_match::MatchVisitor>::check_match::{closure#0}> as core[48d2d63575a1b4fb]::iter::traits::iterator::Iterator>::fold::<(), core[48d2d63575a1b4fb]::iter::traits::iterator::Iterator::for_each::call<rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::usefulness::MatchArm, <alloc[43519ed41124516]::vec::Vec<rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::usefulness::MatchArm> as alloc[43519ed41124516]::vec::spec_extend::SpecExtend<rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::usefulness::MatchArm, core[48d2d63575a1b4fb]::iter::adapters::map::Map<core[48d2d63575a1b4fb]::slice::iter::Iter<rustc_hir[8ae6c0dca9300fdf]::hir::Arm>, <rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::check_match::MatchVisitor>::check_match::{closure#0}>>>::spec_extend::{closure#0}>::{closure#0}>
  25:     0x7f3b64b34a71 - <alloc[43519ed41124516]::vec::Vec<rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::usefulness::MatchArm> as alloc[43519ed41124516]::vec::spec_from_iter::SpecFromIter<rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::usefulness::MatchArm, core[48d2d63575a1b4fb]::iter::adapters::map::Map<core[48d2d63575a1b4fb]::slice::iter::Iter<rustc_hir[8ae6c0dca9300fdf]::hir::Arm>, <rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::check_match::MatchVisitor>::check_match::{closure#0}>>>::from_iter
  26:     0x7f3b63f5423f - <rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::check_match::MatchVisitor as rustc_hir[8ae6c0dca9300fdf]::intravisit::Visitor>::visit_expr
  27:     0x7f3b63f53ecf - <rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::check_match::MatchVisitor as rustc_hir[8ae6c0dca9300fdf]::intravisit::Visitor>::visit_expr
  28:     0x7f3b63f53ee9 - <rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::check_match::MatchVisitor as rustc_hir[8ae6c0dca9300fdf]::intravisit::Visitor>::visit_expr
  29:     0x7f3b63f53883 - rustc_mir_build[24c68b2faf4d7adc]::thir::pattern::check_match::check_match
  30:     0x7f3b641cce0e - rustc_query_system[a211d6db6b7bb5c6]::query::plumbing::try_execute_query::<rustc_query_impl[41c9f61e780c6183]::plumbing::QueryCtxt, rustc_query_system[a211d6db6b7bb5c6]::query::caches::DefaultCache<rustc_span[590a2279fe342e71]::def_id::DefId, ()>>
  31:     0x7f3b64292ed0 - <rustc_query_impl[41c9f61e780c6183]::Queries as rustc_middle[80ce3c200b65c1bf]::ty::query::QueryEngine>::check_match
  32:     0x7f3b63ad7b94 - <rustc_session[1bd44c9aeaf68c2e]::session::Session>::time::<(), rustc_interface[f5b05d2a4419ce67]::passes::analysis::{closure#1}::{closure#0}::{closure#0}>
  33:     0x7f3b64787954 - <rustc_session[1bd44c9aeaf68c2e]::session::Session>::time::<(), rustc_interface[f5b05d2a4419ce67]::passes::analysis::{closure#1}>
  34:     0x7f3b6477adce - rustc_interface[f5b05d2a4419ce67]::passes::analysis
  35:     0x7f3b64c4d9be - rustc_query_system[a211d6db6b7bb5c6]::query::plumbing::try_execute_query::<rustc_query_impl[41c9f61e780c6183]::plumbing::QueryCtxt, rustc_query_system[a211d6db6b7bb5c6]::query::caches::DefaultCache<(), core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>>
  36:     0x7f3b64c90c7e - rustc_query_system[a211d6db6b7bb5c6]::query::plumbing::get_query::<rustc_query_impl[41c9f61e780c6183]::queries::analysis, rustc_query_impl[41c9f61e780c6183]::plumbing::QueryCtxt>
  37:     0x7f3b64754054 - <rustc_interface[f5b05d2a4419ce67]::passes::QueryContext>::enter::<rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>
  38:     0x7f3b6473fd88 - <rustc_interface[f5b05d2a4419ce67]::interface::Compiler>::enter::<rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}::{closure#2}, core[48d2d63575a1b4fb]::result::Result<core[48d2d63575a1b4fb]::option::Option<rustc_interface[f5b05d2a4419ce67]::queries::Linker>, rustc_errors[8f15b138673742da]::ErrorGuaranteed>>
  39:     0x7f3b6475389f - rustc_span[590a2279fe342e71]::with_source_map::<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_interface[f5b05d2a4419ce67]::interface::create_compiler_and_run<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}>::{closure#1}>
  40:     0x7f3b647409b7 - <scoped_tls[6c583823b66fe937]::ScopedKey<rustc_span[590a2279fe342e71]::SessionGlobals>>::set::<rustc_interface[f5b05d2a4419ce67]::interface::run_compiler<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>
  41:     0x7f3b64767e3f - std[f62804d94bf33ed9]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f5b05d2a4419ce67]::util::run_in_thread_pool_with_globals<rustc_interface[f5b05d2a4419ce67]::interface::run_compiler<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>
  42:     0x7f3b64753359 - <<std[f62804d94bf33ed9]::thread::Builder>::spawn_unchecked_<rustc_interface[f5b05d2a4419ce67]::util::run_in_thread_pool_with_globals<rustc_interface[f5b05d2a4419ce67]::interface::run_compiler<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>::{closure#1} as core[48d2d63575a1b4fb]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x7f3b6214cf23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5f2cc5c325bd6f26
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/alloc/src/boxed.rs:1861:9
  44:     0x7f3b6214cf23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1873871631f0e48e
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/alloc/src/boxed.rs:1861:9
  45:     0x7f3b6214cf23 - std::sys::unix::thread::Thread::new::thread_start::he96d38568e3469f7
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys/unix/thread.rs:108:17
  46:     0x7f3b61c866db - start_thread
                               at /build/glibc-CVJwZb/glibc-2.27/nptl/pthread_create.c:463
  47:     0x7f3b617a761f - clone
                               at /build/glibc-CVJwZb/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  48:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0-nightly (76d770ac2 2022-04-02) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_match] match-checking `preset_ns::<impl at src/preset_ns.rs:37:1: 47:2>::get_host_name`
#1 [analysis] running analysis passes on this crate
end of query stack
warning: `smartdns` (bin "smartdns") generated 1 warning
error: could not compile `smartdns`; 1 warning emitted
`````````

**Comment by zxlhhyccc** [comment]
重新git源码编译可以通过，请问大佬有计划支持其他架构吗？

**Comment by mokeyish** [comment]
其他架构应该是支持编译的，你试试用这个编译，https://github.com/cross-rs/cross 

你的编译失败，可能是系统环境依赖问题，是最新的 main 代码么？github action 都打包成功了，也可以试试上面的 cross 。

**Comment by mokeyish** [comment]
> 重新git源码编译可以走下去，但最后还是上面一样失败，请问大佬有计划支持其他架构吗？

会不会是因为路径中文的原因？

**Comment by zxlhhyccc** [comment]
非中文路径编译同样问题。。。。
你说的prefetch在哪个文件中？

**Comment by mokeyish** [comment]
> 非中文路径编译同样问题。。。。 你说的prefetch在哪个文件中？ [https://github.com/cross-rs/cross只能在docker中编译吧。。。](https://github.com/cross-rs/cross%E5%8F%AA%E8%83%BD%E5%9C%A8docker%E4%B8%AD%E7%BC%96%E8%AF%91%E5%90%A7%E3%80%82%E3%80%82%E3%80%82)

在 mw_cache 那里(线上的版本还是固定时间轮训)，我本地已经改成使用 tokio notify 了，这样可以根据 ttl 过期指定时间唤醒检查，新加入的缓存如果过期更早，也可以提前唤醒。

**Comment by zxlhhyccc** [comment]
请问改mw_cache里的哪一行？

**Comment by mokeyish** [comment]
> 请问改mw_cache里的哪一行？

这里前面加 `#` 注释掉就好了
https://github.com/mokeyish/smartdns-rs/blob/d062b2d2df9f4a87f82141640604737a7bd8fca5/tests/example/smartdns.conf#L2

编译的问题, debian 可以安装 `apt install build-essential` 试试。我这边用的是 windows kali roling 的 wsl2 下开发的.

**Comment by zxlhhyccc** [comment]
> > 请问改mw_cache里的哪一行？
> 
> 这里前面加 `#` 注释掉就好了
> 
> https://github.com/mokeyish/smartdns-rs/blob/d062b2d2df9f4a87f82141640604737a7bd8fca5/tests/example/smartdns.conf#L2
> 
> 编译的问题, debian 可以安装 `apt install build-essential` 试试。我这边用的是 windows kali roling 的 wsl2 下开发的.

注释后，编译仍然发生上述错误，我是ubuntu；
安装build-essential后（实际安装了），编译的命令是什么？还是同样的命令吗？

**Comment by mokeyish** [comment]
哦，你用的 nightly 版本，比我的 stable (rustc 1.65.0) 还低？

**Comment by mokeyish** [comment]
你这是 amd64 的架构？你可试试直接从这下载现成的版本。
https://github.com/mokeyish/smartdns-rs/releases/tag/0.1.2

**Comment by mokeyish** [comment]
要更新至最新的 rust 稳定版的。先关闭了，有问题再说
